DemoMyApp/src/objects/CC_Transaction_Results__c.object
<CustomObject>
    <fields>
        <fullName>Action_Code__c</fullName>
        <description>Will come back from Six Cards after a Transaction is completed</description>
        <label>Action Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Text__c</fullName>
        <label>Error Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <description>This will come back from Six Cars after the Transaction is completed</description>
        <label>Transaction ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_State__c</fullName>
        <label>Transaction State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CC Transaction Results</label>
    <nameField>
        <displayFormat>MTN-{0000000000}</displayFormat>
        <label>Merchant Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Transaction Results</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/objects/Finance_Transactions__c.object
<CustomObject>
    <fields>
        <fullName>Action_Code__c</fullName>
        <label>Action Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Last_4__c</fullName>
        <label>Card Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Text__c</fullName>
        <label>Error Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Finance__c</fullName>
        <label>Finance</label>
        <referenceTo>Opportunity_Finance__c</referenceTo>
        <relationshipLabel>Finance Transactions</relationshipLabel>
        <relationshipName>Finance_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Method__c</fullName>
        <label>Transaction Method</label>
        <picklist>
            <picklistValues>
                <fullName>CC Charged Via Salesforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CC Charged via HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>From Top Apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Transaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PaytoStudy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_State__c</fullName>
        <label>Transaction State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manually Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transaction Timed Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmation Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuition Fee Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Writeoff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PtS 1st Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PtS 2nd Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Finance Transaction</label>
    <nameField>
        <displayFormat>FTN-{000000}</displayFormat>
        <label>Finance Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DemoMyApp/src/objects/Opportunity_Finance__c.object
<CustomObject>
    <fields>
        <fullName>App_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>App ID</label>
        <length>6</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Confirmation_Deposit_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmation Deposit Paid?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Application</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Finances</relationshipLabel>
        <relationshipName>Opportunity_Finances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Finance</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DemoMyApp/src/classes/SixCardPaymentController.cls
Public without sharing class SixCardPaymentController
{
    public string TxnID{get;set;}
    public string TxnType{get;set;}
    public string TxnState{get;set;}
    public string ActionCode{get;set;}
    public string ActionMsg{get;set;}
    public string AuthCode{get;set;}
    public string Error_Code{get;set;}
    public string Error_Text{get;set;}
    public string MerchantRef{get;set;}
    public string Card_Type{get;set;}
    public string Card_4Digit{get;set;}
    public String Card_Expiry{get;set;}
    public string financeID{get;set;}
    public string MerchantRef2{get;set;}
    string apid;
    public SixCardPaymentController(){
        if ((ApexPages.currentPage().getParameters().get('trx_merchant_reference') != null) && ApexPages.currentPage().getParameters().get('trx_merchant_reference').trim() != '' ){
                 apid = System.currentPagereference().getParameters().get('trx_merchant_reference');
        }
        else{
                apid =null;
        }
        if (ApexPages.currentPage().getParameters().get('TrxID') != null ){
                 TxnID = System.currentPagereference().getParameters().get('TrxID');
        }
        else{
                TxnID='Not Getting';
         }
         
         if (ApexPages.currentPage().getParameters().get('TrxState') != null ){
                 TxnState = ApexPages.currentPage().getParameters().get('TrxState');
          }
          else{
                TxnState = 'Not Getting';
         }
           
         if (ApexPages.currentPage().getParameters().get('AuthCode') != null ){
                 ActionCode = ApexPages.currentPage().getParameters().get('AuthCode');
            }
         else{
                ActionCode = 'Not Getting';
         }
            
         if (ApexPages.currentPage().getParameters().get('authorise_info_action_message') != null ){
                 ActionMsg = ApexPages.currentPage().getParameters().get('authorise_info_action_message');
          }
          else{
                ActionMsg = 'Not Getting';
          }
           
          if (ApexPages.currentPage().getParameters().get('authorise_info_authorise_code') != null ){
                 AuthCode = ApexPages.currentPage().getParameters().get('authorise_info_authorise_code');
          }
          else {
                AuthCode = 'Not Getting';
          }
            
          if (ApexPages.currentPage().getParameters().get('ErrorCode') != null ){
                 Error_Code = ApexPages.currentPage().getParameters().get('ErrorCode');
          }
          else{
                Error_Code = 'Not Getting';
          }
            
          if (ApexPages.currentPage().getParameters().get('ErrorText') != null ){
                 Error_Text = ApexPages.currentPage().getParameters().get('ErrorText');
          } 
          else{
                Error_Text = 'Not Getting';
          }
           
          if (ApexPages.currentPage().getParameters().get('trx_merchant_reference') != null ){
                 financeID  = ApexPages.currentPage().getParameters().get('trx_merchant_reference');
            }
          else{
                financeID = null;
          }
            
          if (ApexPages.currentPage().getParameters().get('trx_merchant_reference_2') != null ){
                 TxnType = ApexPages.currentPage().getParameters().get('trx_merchant_reference_2');
          }
          else{
                TxnType  = null;
          }
            
          if (ApexPages.currentPage().getParameters().get('CardType') != null ){
                 Card_Type = ApexPages.currentPage().getParameters().get('CardType');
           }
           else{
                Card_Type = 'Not Getting';
           }
            
           if (ApexPages.currentPage().getParameters().get('Card4Digits') != null ){
                 Card_4Digit = ApexPages.currentPage().getParameters().get('Card4Digits');
           }
           else{
                Card_4Digit = '';
           }
             
           if (ApexPages.currentPage().getParameters().get('CardExpiry') != null ){
                 Card_Expiry = ApexPages.currentPage().getParameters().get('CardExpiry');
            }
            else{
                Card_Expiry = null;
            }
    }
    
    public void  PaymentSuccess(){
        if(TxnType=='Application Fee'){
            ApplicationFeeSucess();
        }
        else if(TxnType=='Confirmation Deposit'){
            ConfirmationDepositSucess();        
        }
    }
    
    public void  PaymentFailure(){
          if(TxnType=='Application Fee'){
            ApplicationFeeFailure();
        }
        else if(TxnType=='Confirmation Deposit'){
            ConfirmationDepositFailure();        
        }  
        
    }
    
    public void ConfirmationDepositSucess(){
        try
        {
           // CC_Transaction_Results__c TrnResultSuccess = new CC_Transaction_Results__c();
            Finance_Transactions__c TrnResultSuccess = new Finance_Transactions__c();
            TrnResultSuccess =[select 
                                      Finance__r.Confirmation_Deposit_Paid__c
                                    , Finance__r.Opportunity__r.Paid_Application_Fee__c
                                    , Finance__r.Opportunity__r.Application_Fee_Complete__c  
                                    , Action_Code__c
                                    , Card_Type__c
                                    , Error_Code__c
                                    , Error_Text__c
                                    , Transaction_Method__c
                                    , Transaction_Status__c 
                                    , Expiry_Date__c
                                    , Transaction_ID__c
                                    , Transaction_State__c
                                    , Transaction_Type__c
                                    , Card_Last_4__c  
                                    , Finance__r.Opportunity__r.app_id__c
                                   
                             from Finance_Transactions__c where id=:financeID];              
            TrnResultSuccess.Action_Code__c = ActionCode ;
            TrnResultSuccess.Card_Type__c = Card_Type ;
            TrnResultSuccess.Error_Code__c= Error_Code ;
            TrnResultSuccess.Error_Text__c  = Error_Text ;
            TrnResultSuccess.Expiry_Date__c = Card_Expiry ;
            TrnResultSuccess.Transaction_ID__c = TxnID;
            TrnResultSuccess.Transaction_State__c = TxnState;                
            TrnResultSuccess.Transaction_Type__c = TxnType;            
            TrnResultSuccess.Card_Last_4__c = Card_4Digit;
            TrnResultSuccess.Transaction_Method__c = 'CC Charged Via Salesforce';
            TrnResultSuccess.Transaction_Status__c = 'Success';
            //TrnResultSuccess.App_ID__c = TrnResultSuccess.Finance__r.Opportunity__r.app_id__c;
            upsert TrnResultSuccess;
            // update Finance object flage
            TrnResultSuccess.Finance__r.Confirmation_Deposit_Paid__c = true;
            update TrnResultSuccess.Finance__r;
            
        }
        catch(Exception ex)
        {
            apexpages.addmessages(ex);
        }
    
    }
    
    public void ConfirmationDepositFailure(){
        try
        {
            Finance_Transactions__c TrnResultFailure = new Finance_Transactions__c();
            TrnResultFailure =[select 
                                     Action_Code__c
                                     , Card_Type__c
                                     , Error_Code__c
                                     , Error_Text__c
                                     , Transaction_Method__c
                                     , Transaction_Status__c 
                                     , Expiry_Date__c
                                     , Transaction_ID__c
                                     , Transaction_State__c
                                     , Transaction_Type__c
                                     , Card_Last_4__c  
                                     , Finance__r.Opportunity__r.app_id__c                                    
                                 from Finance_Transactions__c where id=:financeID];              
            TrnResultFailure.Action_Code__c = ActionCode ;
            TrnResultFailure.Card_Type__c = Card_Type ;
            TrnResultFailure.Error_Code__c= Error_Code ;
            TrnResultFailure.Error_Text__c  = Error_Text ;
            TrnResultFailure.Expiry_Date__c = Card_Expiry ;
            TrnResultFailure.Transaction_ID__c = TxnID;
            TrnResultFailure.Transaction_State__c = TxnState;                
            TrnResultFailure.Transaction_Type__c = TxnType;            
            TrnResultFailure.Card_Last_4__c = Card_4Digit;
            TrnResultFailure.Transaction_Method__c = 'CC Charged Via Salesforce';
            //TrnResultFailure.App_ID__c = TrnResultFailure.Finance__r.Opportunity__r.app_id__c;
                if(Error_Text.contains('DECLINE')){
                   TrnResultFailure.Transaction_Status__c = 'Decline';
                }
                else{
                   TrnResultFailure.Transaction_Status__c = 'Error';
                }
            update TrnResultFailure;
            
            
        }
        catch(Exception ex)
        {
            apexpages.addmessages(ex);
        }
    
    }
    
    public void ApplicationFeeSucess(){
        try
        {
           // CC_Transaction_Results__c TrnResultSuccess = new CC_Transaction_Results__c();
            Finance_Transactions__c TrnResultSuccess = new Finance_Transactions__c();
            TrnResultSuccess.Action_Code__c = ActionCode ;
            TrnResultSuccess.Finance__c = financeID ;
            TrnResultSuccess.Card_Type__c = Card_Type ;
            TrnResultSuccess.Error_Code__c= Error_Code ;
            TrnResultSuccess.Error_Text__c  = Error_Text ;
            TrnResultSuccess.Expiry_Date__c = Card_Expiry ;
            TrnResultSuccess.Transaction_ID__c = TxnID;
            TrnResultSuccess.Transaction_State__c = TxnState;                
            TrnResultSuccess.Transaction_Type__c = TxnType;            
            TrnResultSuccess.Card_Last_4__c = Card_4Digit;
            TrnResultSuccess.Transaction_Method__c = 'CC Charged Via Salesforce';
            TrnResultSuccess.Transaction_Status__c = 'Success';
            upsert TrnResultSuccess;            
            
            //Update Application flage
            Finance_Transactions__c TxnResult =[select 
                                      Finance__r.Confirmation_Deposit_Paid__c
                                    , Finance__r.Opportunity__r.Paid_Application_Fee__c
                                    , Finance__r.Opportunity__r.Application_Fee_Complete__c 
                                    , Finance__r.Opportunity__r.app_id__c             
                             from Finance_Transactions__c where id=:TrnResultSuccess.id];
            
            
            TxnResult.Finance__r.Opportunity__r.Paid_Application_Fee__c = true;
            TxnResult.Finance__r.Opportunity__r.Application_Fee_Complete__c = true;
            update TxnResult.Finance__r.Opportunity__r;
            
            /*TxnResult.App_ID__c = TxnResult.Finance__r.Opportunity__r.app_id__c;
            update TxnResult;*/
            
        }
        catch(Exception ex)
        {
            apexpages.addmessages(ex);
        }
    
    }
    
    public void ApplicationFeeFailure(){
        try{
            Finance_Transactions__c TrnResultFailure = new Finance_Transactions__c();
            TrnResultFailure.Action_Code__c = ActionCode ;
            TrnResultFailure.Finance__c = financeID ;
            TrnResultFailure.Card_Type__c = Card_Type ;
            TrnResultFailure.Error_Code__c= Error_Code ;
            TrnResultFailure.Error_Text__c  = Error_Text ;
            TrnResultFailure.Expiry_Date__c = Card_Expiry ;
            TrnResultFailure.Transaction_ID__c = TxnID;
            TrnResultFailure.Transaction_State__c = TxnState;                
            TrnResultFailure.Transaction_Type__c = TxnType;            
            TrnResultFailure.Card_Last_4__c = Card_4Digit;
            TrnResultFailure.Transaction_Method__c = 'CC Charged Via Salesforce';
                if(Error_Text.contains('DECLINE')){
                   TrnResultFailure.Transaction_Status__c = 'Decline';
                }
                else{
                   TrnResultFailure.Transaction_Status__c = 'Error';
                }
            insert TrnResultFailure;
            
          //Update Application flage
           /* Finance_Transactions__c TxnResult =[select Finance__r.Opportunity__r.app_id__c             
                             from Finance_Transactions__c where id=:TrnResultFailure.id];
                       
            TxnResult.App_ID__c = TxnResult.Finance__r.Opportunity__r.app_id__c;
            update TxnResult;*/
            
       }
       catch(Exception ex){
           apexpages.addmessages(ex);
       }
   }
}