DemoMyApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age_Range__c</fullName>
        <description>Age Range from GMAT and other List Imports</description>
        <label>Age Range</label>
        <picklist>
            <picklistValues>
                <fullName>18-22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23-25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26-28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29-32</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>33-40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40-50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Apply_Routing_Type__c</fullName>
        <label>Apply Routing</label>
        <picklist>
            <picklistValues>
                <fullName>Zip/Postal Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proximity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geocoded Proximity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country_Of_Residence_Name__c</fullName>
        <formula>Country_Of_Residence__r.Name</formula>
        <label>Country Of Residence: Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Of_Residence__c</fullName>
        <inlineHelpText>In what country do you currently live?</inlineHelpText>
        <label>Country Of Residence</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Residence)</relationshipLabel>
        <relationshipName>Contacts_By_Residence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department_Name_Primary__c</fullName>
        <formula>Program_Primary__r.Department__r.Name</formula>
        <label>Department Name (Primary)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department_Name_Secondary__c</fullName>
        <formula>Program_Secondary__r.Department__r.Name</formula>
        <label>Department Name (Secondary)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department_Name_Third__c</fullName>
        <formula>Program_third__r.Department__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Department Name (Third)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Do_Not_Route__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Route?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Primary__c</fullName>
        <label>Program (Primary)</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contacts: By Program (Primary)</relationshipLabel>
        <relationshipName>Contacts_By_Program_Primary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Secondary__c</fullName>
        <label>Program (Secondary)</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contacts: By Program (Secondary)</relationshipLabel>
        <relationshipName>Contacts_By_Program_Secondary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_third__c</fullName>
        <label>Program (third)</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contacts (Program (third))</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lat Am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eurasia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Sub-Region</label>
        <picklist>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Load__c</fullName>
        <label>Work Load</label>
        <picklist>
            <picklistValues>
                <fullName>Did Not Respond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive MBA Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full-time Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part-time Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undecided</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

DemoMyApp/src/classes/RouteTestController.cls
public without sharing class RouteTestController 
{
	public RouteTestController()
	{
		String StrID = ApexPages.currentPage().getParameters().get('id');
		List<Contact> contactNewList = [select Name
                 , Age_Range__c
                 , Apply_Routing_Type__c
                 , Department_Name_Primary__c
                 , Department_Name_Secondary__c
                 , Department_Name_Third__c
                 , Country_Of_Residence_Name__c
                 , Country_Of_Residence__c
                 , Do_Not_Route__c
                 , MailingPostalCode
                 , MailingCity
                 , MailingCountry
                 , MailingState
                 , OwnerId
                 , OtherPostalCode
                 , OtherCity
                 , OtherCountry
                 , OtherState
                 , Program_Primary__c
                 , Program_Secondary__c
                 , Program_Third__c
                 , Region__c
                 , Sub_Region__c
                 , Work_Load__c
              from Contact
             where Id =: StrID
            
       /*     List<Lead> contactNewList = [select Name
                 , Age_Range__c
                 , Apply_Routing_Type__c
                 , Department_Name_Primary__c
                 , Department_Name_Secondary__c
                 , Department_Name_Third__c
                 , Country_Of_Residence_Name__c
                 , Country_Of_Residence__c
                 , Do_Not_Route__c
                 , OwnerId
              	,Status
              	,State
              	,LeadSource
                 , Program_Primary__c
                 , Program_Secondary__c
                 , Program_Third__c
                 , Region__c
                 , Sub_Region__c
                 , Work_Load__c
              from Lead
             where Id =: StrID
             */
            
        ];
		//Lead_RouteByRecruiting.applyRouting(contactNewList);
		Contact_RouteByRecruiting.applyRouting(contactNewList);
	}
}