DemoMyApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country_Of_Citizenship_Override__c</fullName>
        <label>Country Of Citizenship Override</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Of_Citizenship__c</fullName>
        <label>Nationality 2</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Citizenship)</relationshipLabel>
        <relationshipName>Contacts_By_Citizenship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Of_Residence_Override__c</fullName>
        <inlineHelpText>If the country does not exist in the list please add the value in the text field provided.</inlineHelpText>
        <label>Country Of Residence Override</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Of_Residence__c</fullName>
        <inlineHelpText>In what country do you currently live?</inlineHelpText>
        <label>Country Of Residence</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Residence)</relationshipLabel>
        <relationshipName>Contacts_By_Residence</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

DemoMyApp/src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Name_Lower_Case__c</fullName>
        <formula>LOWER(Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name (Lower Case)</label>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/classes/Contact_UpdateLookups.cls
public without sharing class Contact_UpdateLookups extends ContactTrigger {
    // ^ ignore profile permissions.
     
    public Contact_UpdateLookups(Contact[] contactOldList, Contact[] contactNewList) {
        super(contactOldList, contactNewList);
    }
    
    public virtual override void execute() {
        executeForCountries();
    }
    
    //
    // The applicant portal UI allows for applicants to pick their countries from a long list, by name. In order to 
    // support this flexibility, we need to match up the name of the country override field to the actual country id.
    // 
    
    void executeForCountries() {
        Map<String, Id> countryMap = new Map<String, Id> {};
        
        for(Contact contactNew : contactNewList) 
        {
        	if (contactNew.Country_Of_Citizenship_Override__c != null)
                countryMap.put(contactNew.Country_Of_Citizenship_Override__c.toLowerCase(), null);
            if (contactNew.Country_Of_Residence_Override__c != null)
                countryMap.put(contactNew.Country_Of_Residence_Override__c.toLowerCase(), null);
        }
        
        for(Country__c country : [
            select Name_Lower_Case__c
              from Country__c
             where Name_Lower_Case__c in :countryMap.keySet()
             limit 10000
        ]) countryMap.put(country.Name_Lower_Case__c, country.Id);
        
        for(Contact contactNew : contactNewList) {
            if (contactNew.Country_Of_Citizenship_Override__c != null)
                contactNew.Country_Of_Citizenship__c = countryMap.get(contactNew.Country_Of_Citizenship_Override__c.toLowerCase());
            if (contactNew.Country_Of_Residence_Override__c != null)
                contactNew.Country_Of_Residence__c = countryMap.get(contactNew.Country_Of_Residence_Override__c.toLowerCase());
        }
    }
}