DemoMyApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country_Of_Citizenship__c</fullName>
        <label>Nationality 2</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Citizenship)</relationshipLabel>
        <relationshipName>Contacts_By_Citizenship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Of_Origin__c</fullName>
        <label>Nationality 1</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Origin)</relationshipLabel>
        <relationshipName>Contacts_By_Origin</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Of_Residence__c</fullName>
        <inlineHelpText>In what country do you currently live?</inlineHelpText>
        <label>Country Of Residence</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Residence)</relationshipLabel>
        <relationshipName>Contacts_By_Residence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Area_Code__c</fullName>
        <label>Home Phone Area Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Country_Code__c</fullName>
        <label>Primary Phone Country Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Main_Number__c</fullName>
        <label>Primary Phone Main Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_English_Listening__c</fullName>
        <label>Language: English Listening</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Reading__c</fullName>
        <label>Language: English Reading</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Speaking__c</fullName>
        <label>Language: English Speaking</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Writing__c</fullName>
        <label>Language: English Writing</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <inlineHelpText>What is the primary language you speak? If you are fluent in English, please select it.</inlineHelpText>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awadhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijani, South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bengali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhojpuri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burmese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Gan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Hakka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Jinyu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Mandarin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Min Nan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Wu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Xiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Yue(Cantonese)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dutch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gujarati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hausa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hindi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Javanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kannada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maithili</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malayalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marathi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oriya</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

DemoMyApp/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Application Requirements</relationshipLabel>
        <relationshipName>Opportunity_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recommendation_Analytical_Ability__c</fullName>
        <label>Recommendation: Analytical Ability</label>
        <picklist>
            <picklistValues>
                <fullName>Outstanding (Top 5%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superior (Top Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average (Middle Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor (Bottom Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recommendation_Background__c</fullName>
        <inlineHelpText>How long have you known the applicant and in what context?</inlineHelpText>
        <label>Recommendation: Background</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recommendation_Comments__c</fullName>
        <inlineHelpText>Please comment on the Applicant as to relevant intellectual and administrative competence, ability to work with others, capacity in oral expression, imagination and probable creativity and other personal qualities that you believe would be helpful to the</inlineHelpText>
        <label>Recommendation: Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recommendation_Contact__c</fullName>
        <label>Recommendation: Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Requirements (Recommendation: Contact)</relationshipLabel>
        <relationshipName>Requirements_By_Recommentation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recommendation_English_Ability__c</fullName>
        <inlineHelpText>Please provide your appraisal of the Applicant&apos;s ability to read, write, understand, and speak English.</inlineHelpText>
        <label>Recommendation: English Ability</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recommendation_Level_Of_Planning__c</fullName>
        <inlineHelpText>In your opinion, how would the applicant benefit from the program?</inlineHelpText>
        <label>Recommendation: Level Of Planning</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recommendation_Personal_Motivation__c</fullName>
        <label>Recommendation: Personal Motivation</label>
        <picklist>
            <picklistValues>
                <fullName>Outstanding (Top 5%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superior (Top Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average (Middle Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor (Bottom Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recommendation_Potential_For_Growth__c</fullName>
        <label>Recommendation: Potential For Growth</label>
        <picklist>
            <picklistValues>
                <fullName>Outstanding (Top 5%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superior (Top Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average (Middle Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor (Bottom Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recommendation_SWOT__c</fullName>
        <inlineHelpText>What do you consider the Applicant&apos;s strength and weaknesses?</inlineHelpText>
        <label>Recommendation: SWOT</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recommendation_Stress_Management__c</fullName>
        <inlineHelpText>This program is very intensive and students often feel highly pressured. Do you think the Applicant will be successful under these conditions?</inlineHelpText>
        <label>Recommendation: Stress Management</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recommendation_Work_Experience__c</fullName>
        <label>Recommendation: Work Experience</label>
        <picklist>
            <picklistValues>
                <fullName>Outstanding (Top 5%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superior (Top Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average (Middle Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor (Bottom Third)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/classes/TestForAppRecommendationController.cls
// test class for ApplicantEducationController
@IsTest
private class TestForAppRecommendationController {
static testMethod void testPosativeEducation() 
    {  
        //get a user with System Administrator profile and with any role
        User userAccount = [ Select id,userroleid from user where profile.name = 'System Administrator' and userroleid!=null and isactive=true limit 1];
        
        // get profile id for 'Applicant Customer Portal User'
        ID ProfileID = [ Select id from Profile where name = 'Applicant Customer Portal User'].id;
        
        //insert country
        Country__c country = new Country__c(Name='Test Country');
        insert country;
        
        // insert program
        Program__c pro=new Program__c(name='MIB-US-Boston',Country__c=country.id);
        insert pro;
        
        // insert account
        Account A1 = new Account(Name = pro.name,ownerid=userAccount.id);
        insert A1;        
        
        
        // insert contact for CPM user
        Contact C1 = new Contact( AccountID = A1.id, FirstName = 'Test', LastName = 'User', 
        email = 'test-user@fakeemail.com' );
        c1.Firstname = 'Test name';
        c1.Gender__c = 'Male';
        c1.Country_Of_Citizenship__c = country.Id;
        c1.Country_Of_Origin__c = country.Id;
        c1.Country_Of_Residence__c = country.Id;
        c1.Birthdate = Date.today();
        c1.LeadSource = 'Alumni';
        c1.mailingstreet = 'test';
        c1.mailingcity = 'New York';
        c1.mailingstate = 'Test';
        c1.mailingpostalcode = '1W2E4R';
        c1.Home_Phone_Country_Code__c = '011';
        c1.Home_Phone_Area_Code__c = '292';
        c1.Home_Phone_Main_Number__c = '2153648';
        c1.Language__c = 'English';
        c1.Language_English_Speaking__c = 'Fluently';
        c1.Language_English_Listening__c = 'Fluently';
        c1.Language_English_Writing__c = 'Fluently';
        c1.Language_English_Reading__c = 'Fluently';
        insert C1;
 
        // Insert User
        User u1 = new User( email='test-user@fakeemail.com', contactid = c1.id, profileid = profileid, 
        UserName='test-user@fakeemail.com', alias='tuser1', CommunityNickName='tuser1', 
        TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', 
        LanguageLocaleKey='en_US', FirstName = 'Test', LastName = 'User' );
        insert u1;
       
       // get current user
        User currentUser = [select id,contact.id, title, firstname, lastname, email FROM User WHERE id=:u1.id ];      
        
           // insert opportunity
           Opportunity opp = new Opportunity();
            opp.Name = 'Test Opportunity';
            opp.Contact__c = currentUser.Contact.Id;
            opp.StageName ='Accepted';
            opp.CloseDate = Date.today();
            opp.Program__c=pro.id;
            opp.Education_Tab_Complete__c=false;            
            insert opp;
            Requirement__c pReq = new Requirement__c();
            pReq.name='Professional Recommentation (1 of 2)';
            pReq.Country__c = country.id;
            insert pReq;
                //Requirement__c r=[select id,name from Requirement__c where id=:pReq limit 1] ;
                Requirement__c req=new Requirement__c();
                req.name = pReq.name;
                req.Recommendation_SWOT__c='dd';
                req.Recommendation_Background__c='test';
                req.Recommendation_Level_Of_Planning__c='test';
                req.Recommendation_Stress_Management__c='test';
                req.Recommendation_Work_Experience__c='test';
                req.Recommendation_Personal_Motivation__c='test';
                req.Recommendation_Potential_For_Growth__c='test';
                req.Recommendation_Analytical_Ability__c='test';
                req.Recommendation_Comments__c='test';
                req.Recommendation_English_Ability__c='test';
                req.Opportunity__c = opp.id;
                //req.contact__c = c1.id;
                req.Parent__c = pReq.id;
               // req.Recommendation_Contact__c =c1.id;
                insert req;
                System.currentPagereference().getParameters().put('contactid',req.id);
                String encoded = EncodingUtil.urlEncode('test-user@fakeemail.com', 'UTF-8');     
                System.currentPagereference().getParameters().put('c',encoded);    
                ApplicationRecommendationController controller = new ApplicationRecommendationController();
                             
                controller.req.Recommendation_SWOT__c='dd';
                controller.req.Recommendation_Background__c='test';
                controller.req.Recommendation_Level_Of_Planning__c='test';
                controller.req.Recommendation_Stress_Management__c='test';
                controller.req.Recommendation_Work_Experience__c='test';
                controller.req.Recommendation_Personal_Motivation__c='test';
                controller.req.Recommendation_Potential_For_Growth__c='test';
                controller.req.Recommendation_Analytical_Ability__c='test';
               controller.req.Recommendation_Comments__c='test';
                controller.req.Recommendation_English_Ability__c='test';           
                controller.saveandcontinue();
                
                controller.req.Recommendation_SWOT__c='';
                controller.req.Recommendation_Background__c='';
                controller.req.Recommendation_Level_Of_Planning__c='';
                controller.req.Recommendation_Stress_Management__c='';
                controller.req.Recommendation_Work_Experience__c=null;
                controller.req.Recommendation_Personal_Motivation__c=null;
                controller.req.Recommendation_Potential_For_Growth__c=null;
                controller.req.Recommendation_Analytical_Ability__c=null;
                controller.req.Recommendation_Comments__c=null;
                controller.req.Recommendation_English_Ability__c=null;           
                controller.saveandcontinue();

         /* System.runAs(currentUser){
            ApplicationRecommendationController controller = new ApplicationRecommendationController();
         } */
     
  
    }
}