DemoMyApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country_Of_Citizenship__c</fullName>
        <label>Nationality 2</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Citizenship)</relationshipLabel>
        <relationshipName>Contacts_By_Citizenship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Of_Origin__c</fullName>
        <label>Nationality 1</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Origin)</relationshipLabel>
        <relationshipName>Contacts_By_Origin</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Of_Residence__c</fullName>
        <inlineHelpText>In what country do you currently live?</inlineHelpText>
        <label>Country Of Residence</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Residence)</relationshipLabel>
        <relationshipName>Contacts_By_Residence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Area_Code__c</fullName>
        <label>Home Phone Area Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Country_Code__c</fullName>
        <label>Primary Phone Country Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Main_Number__c</fullName>
        <label>Primary Phone Main Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_English_Listening__c</fullName>
        <label>Language: English Listening</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Reading__c</fullName>
        <label>Language: English Reading</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Speaking__c</fullName>
        <label>Language: English Speaking</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Writing__c</fullName>
        <label>Language: English Writing</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <inlineHelpText>What is the primary language you speak? If you are fluent in English, please select it.</inlineHelpText>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awadhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijani, South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bengali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhojpuri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burmese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Gan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Hakka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Jinyu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Mandarin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Min Nan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Wu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Xiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Yue(Cantonese)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dutch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gujarati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hausa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hindi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Javanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kannada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maithili</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malayalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marathi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oriya</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

DemoMyApp/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/classes/TestForApplicantNewPasswordController.cls
// test class for ApplicantNewPasswordController
@IsTest
private class TestForApplicantNewPasswordController{
static testMethod void testApplicantNewPassword() 
         {
            User userAccount = [ Select id,userroleid from user where profile.name = 'System Administrator' and userroleid!=null and isactive=true limit 1];
            ID ProfileID = [ Select id from Profile where name = 'Applicant Customer Portal User'].id;
            Program__c pro=new Program__c(name='MIB-US-Boston');
            insert pro;
            Account A1 = new Account(Name = pro.name,ownerid=userAccount.id);
            insert A1;
            
            Country__c country = new Country__c(Name='Test Country');
            insert country;
           
            Contact C1 = new Contact( AccountID = A1.id, FirstName = 'Test', LastName = 'User', 
            email = 'test-user@fakeemail.com' );
            c1.Firstname = 'Test name';
            c1.Gender__c = 'Male';
            c1.Country_Of_Citizenship__c = country.Id;
            c1.Country_Of_Origin__c = country.Id;
            c1.Country_Of_Residence__c = country.Id;
            c1.Birthdate = Date.today();
            c1.LeadSource = 'Alumni';
            c1.mailingstreet = 'test';
            c1.mailingcity = 'New York';
            c1.mailingstate = 'Test';
            c1.mailingpostalcode = '1W2E4R';
            c1.Home_Phone_Country_Code__c = '011';
            c1.Home_Phone_Area_Code__c = '292';
            c1.Home_Phone_Main_Number__c = '2153648';
            c1.Language__c = 'English';
            c1.Language_English_Speaking__c = 'Fluently';
            c1.Language_English_Listening__c = 'Fluently';
            c1.Language_English_Writing__c = 'Fluently';
            c1.Language_English_Reading__c = 'Fluently';
            insert C1;
     
            User u1 = new User( email='test-user@fakeemail.com', contactid = c1.id, profileid = profileid, 
            UserName='test-user@fakeemail.com', alias='tuser1', CommunityNickName='tuser1', 
            TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', 
            LanguageLocaleKey='en_US', FirstName = 'Test', LastName = 'User' );
            insert u1;
            system.setpassword(u1.id,'12345678a');
            System.currentPagereference().getParameters().put('id',u1.id+'12345678a'); 
            ApplicantNewPasswordController controller = new ApplicantNewPasswordController();
            controller.login();
            controller.password='test1234';
            controller.password1='test1234';
            System.currentPagereference().getParameters().put('uid',u1.id); 
            system.assert(controller.ApplicantResetpassword()!=null);
            controller.password='';
            controller.password1='';
            system.assert(controller.ApplicantResetpassword()==null);
            controller.password='test1234';
            controller.password1='test12345';
            system.assert(controller.ApplicantResetpassword()==null);
               
         } 
}