DemoMyApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Agent_Email__c</fullName>
        <label>Indirect Agent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Agent_Name__c</fullName>
        <label>Agent Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant_Email__c</fullName>
        <label>Applicant Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Country_Of_Citizenship__c</fullName>
        <label>Nationality 2</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Citizenship)</relationshipLabel>
        <relationshipName>Contacts_By_Citizenship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Of_Origin__c</fullName>
        <label>Nationality 1</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Origin)</relationshipLabel>
        <relationshipName>Contacts_By_Origin</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Of_Residence__c</fullName>
        <inlineHelpText>In what country do you currently live?</inlineHelpText>
        <label>Country Of Residence</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Residence)</relationshipLabel>
        <relationshipName>Contacts_By_Residence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Area_Code__c</fullName>
        <label>Home Phone Area Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Country_Code__c</fullName>
        <label>Primary Phone Country Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Main_Number__c</fullName>
        <label>Primary Phone Main Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_English_Listening__c</fullName>
        <label>Language: English Listening</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Reading__c</fullName>
        <label>Language: English Reading</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Speaking__c</fullName>
        <label>Language: English Speaking</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Writing__c</fullName>
        <label>Language: English Writing</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_Other__c</fullName>
        <label>Language: Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <inlineHelpText>What is the primary language you speak? If you are fluent in English, please select it.</inlineHelpText>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awadhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijani, South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bengali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhojpuri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burmese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Gan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Hakka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Jinyu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Mandarin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Min Nan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Wu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Xiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Yue(Cantonese)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dutch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gujarati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hausa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hindi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Javanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kannada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maithili</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malayalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marathi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oriya</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Source_User_Supplied__c</fullName>
        <label>Lead Source (User-Supplied)</label>
        <picklist>
            <picklistValues>
                <fullName>banner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brochure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email distribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LinkedIn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newspaper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School Rankings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Search engine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youtube</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mailing_Country__c</fullName>
        <label>Mailing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (Mailing Country)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone_Area_Code__c</fullName>
        <label>Mobile Phone Area Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone_Country_Code__c</fullName>
        <label>Secondary Phone Country Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone_Main_Number__c</fullName>
        <label>Secondary Phone Main Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <label>Nationality - Applicant - OLD</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suffix__c</fullName>
        <label>Suffix</label>
        <picklist>
            <picklistValues>
                <fullName>Jr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isEnglishNative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>English Native Language</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

DemoMyApp/src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Calling_Code__c</fullName>
        <label>Calling Code</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/classes/ApplicantPersonalInformationController.cls
public class ApplicantPersonalInformationController {
    
    public boolean finalsubmit{get;set;}
    public Contact con {get; set;}
    public User currentUser {get; set;}
    public string birthday{get;set;}
    public string birthmonth{get;set;}
    public string birthyear{get;set;}
    private Date birthdate;
    private Opportunity opp {get; set;}
    private Map <Id, Country__c> countries = new Map <Id, Country__c> ([Select Id, Name FROM Country__c]);
    
    public ApplicantPersonalInformationController () {
        
        countries.put (null, new Country__c ()); // to avoid null pointer exception when page loads with no country selected
        con = new Contact ();
        currentUser = new User ();
        opp = new Opportunity ();
        
        
        try {
            currentUser = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
            con = [SELECT Id
                    , Name
                    , FirstName
                    , LastName
                    , Salutation
                    , Email
                    , MailingStreet
                    , MailingCity
                    , MailingState
                    , MailingPostalCode
                    , MailingCountry
                    , Mailing_Country__c
                    , Accountid
                    , Title
                    , Phone
                    , Suffix__c
                    , Gender__c
                    , Country_Of_Citizenship__c
                    , Country_Of_Origin__c
                    , Country_Of_Residence__c
                    , Birthdate
                    , Language__c
                    , isEnglishNative__c
                    , Language_English_Speaking__c
                    , Language_English_Listening__c
                    , Language_English_Writing__c
                    , Language_English_Reading__c
                    , Language_Other__c
                    , Agent_Email__c
                    , Agent_Name__c
                    , Applicant_Email__c
                    , LeadSource
                    , Lead_Source_User_Supplied__c
                    , Nationality__c
                    , Home_Phone_Country_Code__c
                    , Home_Phone_Area_Code__c
                    , Home_Phone_Main_Number__c
                    , Mobile_Phone_Country_Code__c
                    , Mobile_Phone_Area_Code__c
                    , Mobile_Phone_Main_Number__c 
                    
                FROM Contact WHERE Id = :currentUser.ContactId];
                
                //prepopulate fields when page loads
                if (con.Birthdate != null) {
                    birthday = string.valueOF(con.Birthdate.day());
                    birthmonth = string.valueOF(con.Birthdate.month());
                    birthyear = string.valueOF(con.Birthdate.year());
                }
                
                
                
        } catch (Exception e) {
            ApexPages.addmessages (e);
        }
        
        
        List <Opportunity> oppList = new List <Opportunity> ();
        oppList = [SELECT Id, Name FROM Opportunity WHERE Contact__c =:con.Id];
        
        if (oppList.isEmpty()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Warning, 'Please complete Program/Location Section'));
            
        }
        
        
        // to lock visualforce page----
         try {
            ApplicantFinalController contrl= new ApplicantFinalController();
            contrl.getopp();
            finalsubmit=ApplicantFinalController.finalsubmit;
         }
         catch (Exception e){
            ApexPages.addMessages(e);
         }

        
    }
    
    
    
        // Code for country list 
     public List<SelectOption> getclist() {
     integer i=0;
            List<SelectOption> options = new List<SelectOption>();
            List<Country__c> cou=[select id,name from country__c where name != '-Did Not Respond-' order by name asc]; // remove -Did Not Respond- country from picklist
            options.add(new SelectOption('','-Select-'));            
            for(i=0;i<cou.size();i++){
            options.add(new SelectOption(cou[i].id,cou[i].name));            
            }
    
    
            return options;
        } 
        
        //list of states for country of residence
        
        public  List<SelectOption> getStatesList () {
            
            
            return renderStatesList();
        }
        
        private  List<SelectOption> renderStatesList () {
        
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','-Select-')); 
        
        for (States__c s: [SELECT Name, Country__c, StateShortName__c FROM States__c WHERE Country__c = :countries.get(con.Mailing_Country__c).Name ORDER BY Name]) {
            options.add (new SelectOption (s.Name, s.Name));
        }
        
        return options;
    }
     
    
    // Code for country list 
        public List<SelectOption> getcountryCode() {
            integer i=0;
            List<SelectOption> options = new List<SelectOption>();
            List<Country__c> cou=[select id,name,Calling_Code__c from country__c where Calling_Code__c!=null order by name asc];
            options.add(new SelectOption('','-Select-'));            
            for(i=0;i<cou.size();i++){
            options.add(new SelectOption(string.valueof(cou[i].Calling_Code__c),cou[i].name+'('+cou[i].Calling_Code__c+')'));            
            }
    
    
            return options;
        }
        
        
         public PageReference SaveAndContinue() {
            
            if (con.isEnglishNative__c) {
                con.Language_English_Speaking__c = null;
                con.Language_English_Listening__c = null;
                con.Language_English_Writing__c = null;
                con.Language_English_Reading__c = null;
                con.Language__c = 'English';
            }
            
            if (con.firstname==null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter First Name'));
            if ((con.lastname.trim()=='') || (con.lastname==null))
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter Last Name'));
            if (con.Gender__c==null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please select Gender'));
            if (con.Country_Of_Origin__c == null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter Nationality'));
            if (con.Country_Of_Residence__c == null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter Country of Residence'));
           
            if((birthday.trim()=='') ||  (birthmonth.trim()=='') || (birthyear.trim()=='')) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter Birthdate (mm/dd/yyyy)'));
            } else {
                try {
                    birthdate =  date.valueof(birthyear+'-'+birthmonth+'-'+birthday);
                } catch(exception e) {
                    apexpages.addmessages(e);
                }
            }//end if for birthdate
            
            if ((birthdate!=null) && (birthdate>date.today()))
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Birthdate should be less than today date'));
            if (con.Lead_Source_User_Supplied__c==null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please select "Where did you hear about Us?"'));
            if (con.mailingstreet==null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter Street'));
            if (con.mailingcity==null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter City'));
            if (con.mailingstate==null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter State/Province'));
            if (con.mailingpostalcode==null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter Zip/Postal Code'));
            if (con.Mailing_Country__c==null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please select Country'));
    
            if (con.Home_Phone_Country_Code__c==null)
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter phone country code'));
            if ((con.Home_Phone_Main_Number__c==null) || (con.Home_Phone_Main_Number__c.trim()=='')){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter main phone number'));}
            if (con.Language__c==null )
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter your native language'));
            
            if((con.Language__c!=null) && (con.Language__c!='English')) {
                if(con.Language_English_Speaking__c==null)
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please select Speaking Proficiency'));
                if(con.Language_English_Listening__c==null)
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please select Listening Proficiency'));
                if(con.Language_English_Writing__c==null)
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please select Writing  Proficiency'));
                if(con.Language_English_Reading__c==null)
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please select Reading  Proficiency'));
            }
        
            
    
            if (apexpages.hasmessages())
                return null; 
            
          
            
            try { 
                opp = [ SELECT Primary_Program_Choice__c,Primary_Campus__c, stageName
                                ,  Personal_Information_Complete__c
                                , Contact__c, Primary_Interest__c 
                        FROM Opportunity
                        WHERE Contact__c=:con.id ];
                if(countries.get(con.Country_Of_Origin__c).name=='China' && opp.Primary_Program_Choice__c=='Executive MBA' && opp.Primary_Campus__c=='Shanghai') {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Programs offered on Hult\'s Shanghai campus are not available for China nationals. We encourage Chinese nationals to apply to Hult\'s other campuses in Boston, San Francisco,London, and Dubai.'));
                    return null;
                }       
                
                con.Applicant_Email__c=con.email;
                con.Birthdate= birthdate;
                con.MailingCountry = countries.get(con.Mailing_Country__c).Name;
                update con;
                
               
                opp.contact__c = con.id;
                opp.Personal_Information_Complete__c = true;
                update opp;
                return Page.ApplicantEducation;
                
            } catch (Exception e) {
                ApexPages.addMessages(e); 
                return null;
            }

        }
        
        public PageReference SaveAndLogout() {
            if (SaveAndContinue() == null)
                return null; // step2() returning null means there were errors, so drop back to the page.
            return new PageReference('/secur/logout.jsp');
        }
        
        
        public static testMethod void testApplicantPersonalInformation () {
            
            Country__c country = new Country__c (Name='United States');
            insert country;
            
            States__c states = new States__c (Name='Test', StateShortName__c = 'TEST', Country__c = 'United States');
            insert states;
            
            User u = [select Id, Contact.Birthdate, Contact.Language__c, contact.Country_Of_Residence__c,
                                  contact.Country_Of_Origin__c,
                                  contact.mailingstreet,
                                  contact.mailingcity,
                                  contact.mailingstate,
                                  contact.mailingpostalcode,
                                  contact.mailingcountry,
                                  contact.mailing_country__c,
                                  contact.isEnglishNative__c
                                  from User where isActive=true AND ContactId != null LIMIT 1];
            // populate required field
            
            u.contact.birthdate = System.Today();
            u.contact.language__c = 'English';
            u.contact.Gender__c = 'Male';
            u.contact.Country_Of_Origin__c = country.Id;
            u.contact.Country_Of_Residence__c = country.Id;
            u.contact.MailingStreet = '123';
            u.contact.MailingCity = '123';
            u.contact.MailingState = 'Minnesota';
            u.contact.MailingPostalCode = '55555';
            u.contact.MailingCountry = 'United States';
            u.contact.Mailing_Country__c = country.id;
            u.contact.Language__c = 'English';
            u.contact.isEnglishNative__c = true;
            
            update u.contact;
            
            System.runAs(u){
                ApplicantPersonalInformationController test = new ApplicantPersonalInformationController ();
                test.birthday = '02';
                test.birthmonth = '11';
                test.birthyear = '1988';
                test.getclist();
                test.getcountrycode();
                test.getStatesList();
                test.saveAndContinue();
                test.SaveAndLogout();
            }
        }
        
        
}