DemoMyApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country_Of_Citizenship__c</fullName>
        <label>Nationality 2</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Citizenship)</relationshipLabel>
        <relationshipName>Contacts_By_Citizenship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Of_Origin__c</fullName>
        <label>Nationality 1</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Origin)</relationshipLabel>
        <relationshipName>Contacts_By_Origin</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Of_Residence__c</fullName>
        <inlineHelpText>In what country do you currently live?</inlineHelpText>
        <label>Country Of Residence</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Residence)</relationshipLabel>
        <relationshipName>Contacts_By_Residence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Area_Code__c</fullName>
        <label>Home Phone Area Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Country_Code__c</fullName>
        <label>Primary Phone Country Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Main_Number__c</fullName>
        <label>Primary Phone Main Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_English_Listening__c</fullName>
        <label>Language: English Listening</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Reading__c</fullName>
        <label>Language: English Reading</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Speaking__c</fullName>
        <label>Language: English Speaking</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_English_Writing__c</fullName>
        <label>Language: English Writing</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <inlineHelpText>What is the primary language you speak? If you are fluent in English, please select it.</inlineHelpText>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awadhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijani, South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bengali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhojpuri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burmese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Gan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Hakka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Jinyu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Mandarin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Min Nan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Wu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Xiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese, Yue(Cantonese)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dutch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gujarati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hausa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hindi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Javanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kannada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maithili</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malayalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marathi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oriya</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

DemoMyApp/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>ContactPerson__c</fullName>
        <label>Contact Person</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Family_Sponsor__c</fullName>
        <label>Family Sponsor</label>
        <picklist>
            <controllingField>Sponser__c</controllingField>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Parents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PhoneAreaCode__c</fullName>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhoneNo__c</fullName>
        <label>Main No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Country_Code__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Requirements (Country)</relationshipLabel>
        <relationshipName>Requirements2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponser__c</fullName>
        <label>Who will sponsor/fund your education?</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization other than Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undetermined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SponsorerAddress__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <recordTypes>
        <fullName>Sponsorship</fullName>
        <active>true</active>
        <label>Sponsorship</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/classes/TestForApplicantSponsorshipController.cls
@IsTest
private class TestForApplicantSponsorshipController {
    static testmethod void testCase(){
        User userAccount = [ Select id,userroleid from user where profile.name = 'System Administrator' and userroleid!=null and isactive=true limit 1];
        ID ProfileID = [ Select id from Profile where name = 'Applicant Customer Portal User'].id;
        Program__c pro=new Program__c(name='MIB-US-Boston');
        insert pro;
        Account A1 = new Account(Name = pro.name,ownerid=userAccount.id);
        insert A1;
        
        Country__c country = new Country__c(Name='Test Country');
        insert country;
        List<Contact> ContactList = new List<Contact>();
        Contact C1 = new Contact( AccountID = A1.id, FirstName = 'Test', LastName = 'User', 
        email = 'test-user@fakeemail.com' );
        c1.Firstname = 'Test name';
        c1.Gender__c = 'Male';
        c1.Country_Of_Citizenship__c = country.Id;
        c1.Country_Of_Origin__c = country.Id;
        c1.Country_Of_Residence__c = country.Id;
        c1.Birthdate = Date.today();
        c1.LeadSource = 'Alumni';
        c1.mailingstreet = 'test';
        c1.mailingcity = 'New York';
        c1.mailingstate = 'Test';
        c1.mailingpostalcode = '1W2E4R';
        c1.Home_Phone_Country_Code__c = '011';
        c1.Home_Phone_Area_Code__c = '292';
        c1.Home_Phone_Main_Number__c = '2153648';
        c1.Language__c = 'English';
        c1.Language_English_Speaking__c = 'Fluently';
        c1.Language_English_Listening__c = 'Fluently';
        c1.Language_English_Writing__c = 'Fluently';
        c1.Language_English_Reading__c = 'Fluently';
        insert C1;
 
        User u1 = new User( email='test-user@fakeemail.com', contactid = c1.id, profileid = profileid, 
                UserName='test-user@fakeemail.com', alias='tuser1', CommunityNickName='tuser1', 
        TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', 
        LanguageLocaleKey='en_US', FirstName = 'Test', LastName = 'User' );
        insert u1;
        User u=[select Id, ContactId from User where id=:u1.id limit 1];
        try{
        Opportunity opp1 = new Opportunity();
            opp1.Name = 'Test Opportunity';
            opp1.Contact__c = u.ContactId;
            opp1.StageName ='Accepted';
            opp1.CloseDate = Date.today();
            insert opp1;} catch (exception e){}
        System.runAs(u){
            RecordType recid=[select id from recordtype where name='Sponsorship' and sobjectType='Requirement__c'];
            ApplicantSponsorshipController contr = new ApplicantSponsorshipController();
            contr.req.Name= 'Test Requirement';
            contr.req.Contact__c = u.ContactId;
            contr.req.RecordTypeId = recid.Id;
            contr.Sponser_c = 'Employer';
            contr.req.ContactPerson__c = 'Test person';
            contr.req.SponsorerAddress__c = 'Test Address';
            contr.req.Phone_Country_Code__c = country.id;
            contr.req.PhoneAreaCode__c = '123';
            contr.req.PhoneNo__c = '123456';
            contr.req.Family_Sponsor__c='N/A';
            system.assert(contr.getcountryCode()!=null);   
            contr.issetself();
            contr.getItems();
            system.assert(contr.saveandcontinue()!=null);            
            
            system.assert(contr.saveandcontinueandlogout()!=null);
            contr.req.Name= 'Test Requirement';
            contr.req.Contact__c = u.ContactId;
            contr.req.RecordTypeId = recid.Id;
            contr.req.Sponser__c = 'Self';           
            contr.saveandcontinue();
            contr.req.Name= 'Test Requirement';
            contr.req.Contact__c = u.ContactId;
            contr.req.RecordTypeId = recid.Id;
            contr.req.Sponser__c = 'Employer';
            contr.req.ContactPerson__c = null;
            contr.req.SponsorerAddress__c = null;
            contr.req.Phone_Country_Code__c = null;
            contr.req.PhoneAreaCode__c = null;
            contr.req.PhoneNo__c = null;
            contr.req.Family_Sponsor__c=null;
           // system.assert(contr.saveandcontinue()==null);
            
            
        } 
    }
}