DemoMyApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Applicant_Email__c</fullName>
        <label>Applicant Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Country_Of_Citizenship__c</fullName>
        <label>Nationality 2</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Citizenship)</relationshipLabel>
        <relationshipName>Contacts_By_Citizenship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Of_Residence__c</fullName>
        <inlineHelpText>In what country do you currently live?</inlineHelpText>
        <label>Country Of Residence</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts (By Residence)</relationshipLabel>
        <relationshipName>Contacts_By_Residence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Primary__c</fullName>
        <label>Program (Primary)</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contacts: By Program (Primary)</relationshipLabel>
        <relationshipName>Contacts_By_Program_Primary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Term__c</fullName>
        <label>Start Term</label>
        <picklist>
            <picklistValues>
                <fullName>September 2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>January 2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September 2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>January 2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September 2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>January 2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September 2014</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

DemoMyApp/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/classes/Lead_EmailDuplicatePreventerTest.cls
@IsTest 
private class Lead_EmailDuplicatePreventerTest { 
    public static final Country__c  country = [select Id, Name from Country__c limit 1]; 

    @IsTest
    public static void test1() {
        final String EMAIL_MIXED_CASE = 'TestContact@test1.com';
        final String EMAIL_LOWER_CASE = EMAIL_MIXED_CASE.toLowerCase();
          
        Account account = [select Id from Account limit 1];
        Program__c program = [select Id from Program__c limit 1];
        
        Contact contacts1 = new Contact();
        contacts1.LastName = 'TestContact';
        contacts1.Email = EMAIL_MIXED_CASE;
        contacts1.Applicant_Email__c = EMAIL_MIXED_CASE;
        contacts1.AccountId = account.Id;
        contacts1.Program_Primary__c = program.Id;
        contacts1.Country_Of_Residence__c = country.Id;
        contacts1.Start_Term__c = 'Undecided';
        insert contacts1;
        
        System.debug('::Lead_EmailDuplicatePreventerTest::test1() ::contacts1.Email ==>'+contacts1.Email);
        system.assertEquals( EMAIL_LOWER_CASE, [
            select Email
              from Contact
             where Id = :contacts1.Id
        ].Email);
        
        Lead lead1 = new Lead();
        lead1.FirstName = 'FirstName1';
        lead1.LastName = 'LastName1';
        lead1.Company = 'Company1';
        lead1.Email = 'testcontact@test2.com';
        lead1.Applicant_Email__c = 'testcontact@test2.com';
        lead1.LeadSource = 'Alumni';
        lead1.Status = 'Contacted';
        lead1.Country_Of_Citizenship__c = country.id;
        lead1.Country_Of_Residence__c = country.id;
        lead1.Program_Primary__c = program.id;
        insert lead1;
        
        Lead lead2 = new Lead();
        lead2.FirstName = 'FirstName1';
        lead2.LastName = 'LastName1';
        lead2.Company = 'Company1';
        lead2.Email = '';
        lead2.Applicant_Email__c = 'testcontact@test3.com';
        lead2.LeadSource = 'Alumni';
        lead2.Status = 'Contacted';
        lead2.Country_Of_Citizenship__c = country.id;
        lead2.Country_Of_Residence__c = country.id;
        lead2.Program_Primary__c = program.id;
        insert lead2; 
        
        try {
            lead2.Email = EMAIL_MIXED_CASE;
            update lead2;
          } catch (System.dmlException e) {
            System.debug ('Updating with duplicate failed !!!  This is good');
        }
    } 
 }