DemoMyApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Sponsor_Address__c</fullName>
        <inlineHelpText>Sponsor or Legal Guardian Address</inlineHelpText>
        <label>DONOTUSESponsor/Legal Guardian: Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sponsor_Contact_Person__c</fullName>
        <inlineHelpText>Sponsor or Legal Guardian Name</inlineHelpText>
        <label>DONOTUSESponsor/Legal Guardian</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Employer_or_Organization__c</fullName>
        <inlineHelpText>Sponsor or Guardian Employer name or Organization Name</inlineHelpText>
        <label>DONOTUSESponsor/Guardian: Employer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Fax_Number__c</fullName>
        <label>DONOTUSESponsor/Guardian: Fax Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sponsor_Job_Title__c</fullName>
        <label>DONOTUSESponsor/Guardian: Job Title</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Phone_Number__c</fullName>
        <inlineHelpText>Sponsor or Guardian phone number</inlineHelpText>
        <label>DONOTUSESponsor/Guardian: Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sponsor_of_Education__c</fullName>
        <label>DONOTUSESponsor of Education</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization other then Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undetermined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

DemoMyApp/src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Calling_Code__c</fullName>
        <label>Calling Code</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>ContactPerson__c</fullName>
        <label>Contact Person</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee or Organization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family_Sponsor__c</fullName>
        <label>Family Sponsor</label>
        <picklist>
            <controllingField>Sponser__c</controllingField>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Parents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FaxAreaCode__c</fullName>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FaxNo__c</fullName>
        <label>Main No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax_CountryCode__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Requirements (Country)</relationshipLabel>
        <relationshipName>Requirements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PhoneAreaCode__c</fullName>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhoneNo__c</fullName>
        <label>Main No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Country_Code__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Requirements (Country)</relationshipLabel>
        <relationshipName>Requirements2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponser__c</fullName>
        <label>Who will sponsor/fund your education?</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization other than Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undetermined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SponsorerAddress__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <recordTypes>
        <fullName>Education</fullName>
        <active>true</active>
        <label>Education</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sponsorship</fullName>
        <active>true</active>
        <label>Sponsorship</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/classes/ApplicantSponsorshipController.cls
public without sharing class ApplicantSponsorshipController {
public User user{get;set;}
public Requirement__c req{get;set;}
public String nomap{get;set;}
public String recordtypeid;
public recordType recid;
public Opportunity opp{get;set;}
public boolean tab2{get;set;}
public boolean finalsubmit{get;set;}
public boolean selfset{get;set;}
public string proName{get;set;}
public string Sponser_c{get;set;}
public ApplicantSponsorshipController(){
nomap='No map';
recid=[select id,name from recordtype where name='Sponsorship' and sobjectType='Requirement__c'];
user = [SELECT contact.id, contact.Sponsor_Of_Education__c, 
        contact.Sponsor_Employer_or_Organization__c, 
        contact.Sponsor_Contact_Person__c, contact.Sponsor_Job_Title__c,
        contact.Sponsor_Address__c, contact.Sponsor_Phone_Number__c,
        contact.Sponsor_Fax_Number__c FROM User
                WHERE id = :UserInfo.getUserId()];
          try{
        req=[select id,name,
         Sponser__c,
         Employee__c,
         ContactPerson__c,
         Title__c,
         SponsorerAddress__c,
         Phone_Country_Code__c,
         Fax_CountryCode__c,
         PhoneAreaCode__c,
         FaxAreaCode__c,
         PhoneNo__c,
         FaxNo__c,
         Family_Sponsor__c
         from Requirement__c where contact__c=:user.contact.id and recordtypeid=:recid.id]; 
         Sponser_c=req.Sponser__c;
        // req.Sponser__c=Sponser_c;
           issetself();
            } catch(exception e){req=new Requirement__c();}  
            try{
         opp=[select id,Program_and_Location_Tab_Complete__c,Sponsor_of_Education__c from Opportunity where contact__c=:user.contact.id limit 1];
        // Primary_Program_Choice_c=opp.Primary_Program_Choice__c;
         if(opp.Program_and_Location_Tab_Complete__c==true)
                 {tab2=true;}
                 
                  } catch (exception e) {Opportunity opp = new Opportunity();} 
// to lock visualforce page----
                 try{
                 ApplicantFinalController contrl= new ApplicantFinalController();
                 contrl.getopp();
                 proName=contrl.proName;
                 finalsubmit=ApplicantFinalController.finalsubmit;}
                 catch(exception e){}
}

public List<SelectOption> getItems() 
{
List<SelectOption> options = new List<SelectOption>();
Schema.DescribeFieldResult F = Requirement__c.Sponser__c.getDescribe();
List<Schema.PicklistEntry> P = F.getPicklistValues();
options.add(new SelectOption('','--Select--'));            
for(Schema.PicklistEntry pickListvalues : P){
if((proName!='Bachelor of International Business Administration-UK-London') || (pickListvalues.getvalue()!='Employer'))
{
options.add(new SelectOption(pickListvalues.getvalue(),pickListvalues.getvalue()));            
}
}


return options;
}

    public void issetself()
    {
        if((Sponser_c=='') || (Sponser_c==null) || (Sponser_c=='Self') || (Sponser_c=='Undetermined'))
        {
        selfset=false;
        }
        else
        {
        selfset=true;
        }
        system.debug('*******'+selfset);
    }
    
public pagereference saveandcontinue()
{

            if(Sponser_c==null)
            {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please select Who will sponsor/fund your education?'));
            }
            
            if ((Sponser_c!=null) && (Sponser_c!='Self') && (Sponser_c!='Undetermined'))
            {
                    if((req.Family_Sponsor__c==null) && (Sponser_c=='Family'))
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please select Family Sponsor'));
                    }
                    
                    /*
                    if(req.ContactPerson__c==null)
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter Contact Person'));
                    }
                   if(req.SponsorerAddress__c==null)  
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter Address'));
                    }
                  if(req.Phone_Country_Code__c==null)
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please select Country'));
                    }
         
                  if(req.PhoneNo__c==null)
                    {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.error,'Please enter Main Number'));
                    }
                    */
            }  
 if(!apexpages.hasmessages()) 
            {
            if (Sponser_c=='Self')
            {
            req.Family_Sponsor__c=null;
            req.ContactPerson__c=null;
            req.SponsorerAddress__c=null;
            req.Phone_Country_Code__c=null;
            req.PhoneNo__c=null;
            req.Employee__c=null;
            req.Title__c=null;
            req.Fax_CountryCode__c=null;
            req.FaxNo__c=null;
            }       
            opp.Sponsorship_Tab_Complete__c=true;
            opp.Sponsor_of_Education__c = Sponser_c;
            update opp;
            req.recordtypeid=recid.id;
            req.Sponser__c=Sponser_c;
            req.contact__c=user.contact.id;
            req.Opportunity__c=opp.id;
            req.name='Sponsorship';
            upsert req;
            return page.ApplicantPersonalStatement;
            
}
else
{
return null;
}
}
public PageReference saveandcontinueandlogout() {
        if (saveandcontinue() == null)
            return null; // step2() returning null means there were errors, so drop back to the page.
        return new PageReference('/secur/logout.jsp');
    }

// Code for country list 
 public List<SelectOption> getcountryCode() {
 integer i=0;
        List<SelectOption> options = new List<SelectOption>();
        List<Country__c> cou=[select id,name,Calling_Code__c from country__c where Calling_Code__c!=null order by name asc];
        options.add(new SelectOption('','-Select-'));            
        for(i=0;i<cou.size();i++){
        options.add(new SelectOption(string.valueof(cou[i].id),cou[i].name+'('+cou[i].Calling_Code__c+')'));            
        }


        return options;
    } 
    
}