DemoMyApp/src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Calling_Code__c</fullName>
        <label>Calling Code</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lat Am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nor Am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eurasia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DemoMyApp/src/classes/Contact_RouteByRecruitingTest.cls
@IsTest
private class Contact_RouteByRecruitingTest 
{
	static testmethod void AnalysContact_RouteByRecrutingTest()
	{
		test.startTest();
		
		ID ProfileID = [ Select id from Profile][0].id;
		
		 User objUser = new User( email='test-user@fakeemail.com', profileid = profileid, 
                			UserName='test-user@fakeemail.com', alias='tuser1', CommunityNickName='tuser1', 
        					TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', 
        					LanguageLocaleKey='en_US', FirstName = 'Test', LastName = 'User' );
        insert objUser;
		
		// Create Country 
		Country__c objCountry = new Country__c( Name = 'DemoCountry',Calling_Code__c = 00,Country_Code__c  = 'pp',Region__c = 'MEA11');
        insert objCountry;
		
		//Create Department Data
        Department__c objDept = new Department__c(Name = 'TestMBA');
        insert objDept;
		
		// Created Country Requirement 
		Requirement__c objReqCountry = new Requirement__c(Name = 'CR',Country__c = objCountry.Id);
        insert objReqCountry;
		
		// Created Program
		Program__c objProgram = new Program__c(Name = 'TestProgram',Country__c= objCountry.Id,Department__c = objDept.Id);
        insert objProgram;
		
		
		test.stopTest();
	}
}