DemoMyApp/src/objects/Opportunity_Finance__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Opportunity__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <label>Finance</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DemoMyApp/src/classes/UpdateInstallmentPlan_TestClass.cls
@isTest(SeeAllData=true)
    private class UpdateInstallmentPlan_TestClass {
        public static testMethod void validate_UpdateInstallmentPlan() {

        Opportunity opp= [select id from Opportunity where id = '006U00000030BRf'];      
        
        Opportunity_Finance__c oppFin= [select id from Opportunity_Finance__c where id = 'a0XU0000000A50c']; 
        
        opp.Program__c = 'a0JU00000009Jm9';
        update opp;
        
        opp.Program__c = 'a0JU00000009Jm0';
        update opp;
        
        update oppFin;
        }
    }